const quotes = [
  { text: "The limits of my language mean the limits of my world.", author: "Ludwig Wittgenstein" },
  { text: "To have another language is to possess a second soul.", author: "Charlemagne" },
  { text: "Language is the road map of a culture. It tells you where its people come from and where they are going.", author: "Rita Mae Brown" },
  { text: "A different language is a different vision of life.", author: "Federico Fellini" },
  { text: "Learning another language is not only learning different words for the same things, but learning another way to think about things.", author: "Flora Lewis" },
  { text: "One language sets you in a corridor for life. Two languages open every door along the way.", author: "Frank Smith" },
  { text: "You can never understand one language until you understand at least two.", author: "Geoffrey Willans" },
  { text: "The more languages you know, the more you are human.", author: "Tomáš Garrigue Masaryk" },
  { text: "Language is the blood of the soul into which thoughts run and out of which they grow.", author: "Oliver Wendell Holmes" },
  { text: "He who knows no foreign languages knows nothing of his own.", author: "Johann Wolfgang von Goethe" },
  { text: "With languages, you are at home anywhere.", author: "Edmund de Waal" },
  { text: "A language is an exact reflection of the character and growth of its speakers.", author: "Cesar Chavez" },
  { text: "Learn a new language and get a new soul.", author: "Czech proverb" },
  { text: "Knowledge of languages is the doorway to wisdom.", author: "Roger Bacon" },
  { text: "Language is the dress of thought.", author: "Samuel Johnson" },
  { text: "If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart.", author: "Nelson Mandela" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Mistakes are proof that you are trying.", author: "Unknown" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Your attitude, not your aptitude, will determine your altitude.", author: "Zig Ziglar" }
];
